/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import javafx.fxml.FXMLLoader;
import javafx.application.Application;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.awt.*;

public class App extends Application {

    public void start(Stage stage) {
        try {
            Parent root = FXMLLoader.load(getClass().getResource("/scenesfxml/mainMenuView.fxml"));
            Scene scene = new Scene(root);
            scene.getStylesheets().add(getClass().getResource("/gameAppStyle.css").toExternalForm());
            stage.setTitle("t6ddy-gamas");
            //stage.getIcons().add(getClass().getResource("/gameAppStyle.css").toExternalForm());
            stage.setScene(scene);
            stage.show();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        launch(args);
    }
}
